services:
  - type: web
    name: phishing-url-detection
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    region: singapore  
    envVars:
      - key: FLASK_ENV
        value: production
